basic_settings:
  site_title: PROTEUS Framework
  favicon_image: /assets/img/brand/PROTEUS_black_on_white_logo_only.png

header_settings:
  logo_image: /assets/img/brand/PROTEUS_white_on_black.png
  mobile_logo_image: /assets/img/brand/PROTEUS_black_on_white.png
  # Choose a color for your header [blue, dark, light].
  theme: dark
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "yes"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # papers – use your papers as the home page
  theme: landing

blog_settings:
  # Choose a format for your papers listings:
    # basic – a simple list of papers
    # narrow – a masonary grid of papers
    # grid – a full-width square grid of papers
  theme: basic
  # Should we display a narrow grid of other papers at the bottom of each paper?
  read_more: "yes"

# Setup your navigation below – how to use the icons: 
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket. 
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work! 
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
      # submenu_items:
      # - title: Landing Page
      #   url: /
      #   icon: ni-spaceship text-success    
      # - title: Papers
      #   url: /papers
      #   icon: ni-books text-primary
    - title: 'Docs'
      url: 'https://fwl-proteus.readthedocs.io/en/latest/'
      icon: ni-book-bookmark text-primary
    - title: 'Policy'
      url: '/policy'
      icon: ni-settings-gear-65 text-default
    - title: 'Demo'
      url: '/demo'
      icon: ni-laptop text-danger
    - title: 'Help'
      url: '/help'
      icon: ni-support-16 text-primary
    - title: Modules
      url: /modules        
    - title: 'Papers'
      url: 'https://scixplorer.org/public-libraries/EVAJ1UgWTCy2Z7TRoSmjtQ'
      icon: ni-book-bookmark text-primary
    - title: 'People & Contact'
      url: '/people'

footer_settings:
  footer_tagline: PROTEUS framework for planetary evolution

contact_settings:
  form_action: 'https://formspree.io/hello@jekyllthemes.io'
  confirmation_url: '/thanks'
  email_subject: 'Contact form submission'
  send_button_text: 'Send Message'

social_settings:
  facebook_url: ''
  twitter_url: ''
  instagram_url: ''
  youtube_url: ''
  vimeo_url: ''
  pinterest_url: ''
  tumblr_url: ''
  dribbble_url: ''
  behance_url: ''
  github_url: 'https://github.com/FormingWorlds/PROTEUS'
  reddit_url: ''
  linkedin_url: ''

authors:
  nicholls:
    name: Harrison Nicholls
  lichtenberg:
    name: Tim Lichtenberg

advanced_settings:
  analytics_code: 
  header_js: 
  footer_js: 